compleat contacts, currentContact, findContact
crascot/test_chat pull request #3
Opened 2022-05-18 14:25 UTC by crascot

2022-05-18 15:21 UTC, QuadradS commented on src/components/blocks/second-block/peoples/peoples.jsx
> +        <div className='peoples' onClick={currentId}>
функции называй onCurrentUser

2022-05-25 11:48 UTC, QuadradS requested changes

2022-05-25 11:48 UTC, QuadradS commented on src/components/blocks/fourth-block/fourthBlock.jsx
> +                <div style={{ width: '100%' }}>
Тут еще есть

2022-06-08 09:58 UTC, QuadradS commented on src/components/blocks/second-block/peoples/peoples.jsx
> +        <div className='peoples' onClick={currentId}>
узнай как называются методы в реакт обычно пишу on + название метода

2022-06-08 10:57 UTC, crascot commented on src/components/blocks/third-block/send/send.jsx
> +        dispatch(writeMessage(''))
очищает поле инпут после отправки

2022-06-12 09:03 UTC, merged